apiVersion: v1
kind: Secret
metadata:
  name: workload-git-auth
  namespace: tap-install
type: Opaque
stringData:
  content.yaml: |
    git:
      ingress_domain: tap.aws.samarsinghal.com
      host: https://github.com
      username: samarsinghal
      password: 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
